name: Code Quality

on: workflow_call

jobs:
  ruff_format:
    runs-on: ubuntu-latest
    name: ruff format
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      - name: Install the project
        run: uv sync --upgrade
      - name: Run ruff format
        run: uv run ruff format --diff

  ruff_check:
    runs-on: ubuntu-latest
    name: ruff check
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      - name: Install the project
        run: uv sync --upgrade
      - name: Run ruff check
        run: uv run ruff check --diff

  # pyright:
  #   runs-on: ubuntu-latest
  #   name: pyright
  #   steps:
  #     - uses: actions/checkout@v5
  #     - name: Install uv
  #       uses: astral-sh/setup-uv@v7
  #       with:
  #         enable-cache: true
  #         cache-dependency-glob: "uv.lock"
  #     - name: Set up Python
  #       uses: actions/setup-python@v6
  #       with:
  #         python-version-file: "pyproject.toml"
  #     - name: Install the project
  #       run: uv sync --upgrade --extra tests
  #     - name: Run pyright
  #       run: uv run pyright

  mypy:
    runs-on: ubuntu-latest
    name: mypy
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      - name: Install the project
        run: uv sync --upgrade --extra tests
      - name: Run mypy
        run: uv run mypy
